Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.ssh.forward_agent = true

  # Want to cd there because that directory is by default synced with
  # directory of this Vagrant file.
  # https://stackoverflow.com/questions/17864047
  config.ssh.extra_args = ["-t", "cd /vagrant; bash --login"]
end
